name: Deploy to AWS

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Check and delete stack if in ROLLBACK_COMPLETE state
        run: |
          # Check if stack exists and is in ROLLBACK_COMPLETE state
          if aws cloudformation describe-stacks --stack-name text-to-sql-chatbot --region ap-south-1 2>&1 | grep -q "ROLLBACK_COMPLETE"; then
            echo "Stack is in ROLLBACK_COMPLETE state. Deleting stack before redeployment..."
            aws cloudformation delete-stack --stack-name text-to-sql-chatbot --region ap-south-1
            echo "Waiting for stack deletion to complete..."
            aws cloudformation wait stack-delete-complete --stack-name text-to-sql-chatbot --region ap-south-1
            echo "Stack deletion completed."
          elif aws cloudformation describe-stacks --stack-name text-to-sql-chatbot --region ap-south-1 2>&1 | grep -q "does not exist"; then
            echo "Stack does not exist. Proceeding with deployment."
          else
            echo "Stack exists but is not in ROLLBACK_COMPLETE state. Proceeding with update."
          fi
      
      - name: Debug - Check S3 Bucket
        run: |
          # Create S3 bucket for deployment if it doesn't exist
          aws s3api create-bucket \
            --bucket lambda-deployment-$(aws sts get-caller-identity --query Account --output text)-ap-south-1 \
            --region ap-south-1 \
            --create-bucket-configuration LocationConstraint=ap-south-1 || true
          
          # List buckets to confirm
          aws s3 ls
      
      - name: Prepare Lambda package
        run: |
          chmod +x prepare-lambda.sh
          ./prepare-lambda.sh
      
      - name: Debug - List Zip Contents
        if: always()
        run: |
          echo "Listing top-level contents of text-to-sql-chatbot.zip:"
          ls -l text-to-sql-chatbot.zip
          unzip -l text-to-sql-chatbot.zip | head -n 20
          echo "-------------------------------------"
          echo "Checking for flask specifically in zip:"
          unzip -l text-to-sql-chatbot.zip | grep -i flask || echo "Flask not found in zip list"
      
      - name: Debug - Check Lambda Package
        run: |
          # Check if Lambda package was created and uploaded
          aws s3 ls s3://lambda-deployment-$(aws sts get-caller-identity --query Account --output text)-ap-south-1/
      
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation.yaml \
            --stack-name text-to-sql-chatbot \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides \
              SecretName=text-to-sql-chatbot-secrets \
            --region ap-south-1
      
      - name: Debug - Check Stack Events on Failure
        if: ${{ failure() }}
        run: |
          aws cloudformation describe-stack-events \
            --stack-name text-to-sql-chatbot \
            --region ap-south-1 \
            --query "StackEvents[?contains(ResourceStatus, 'FAILED')].{Status:ResourceStatus,Type:ResourceType,LogicalID:LogicalResourceId,Reason:ResourceStatusReason}" \
            --output table
      
      - name: Get deployment outputs
        id: get-outputs
        run: |
          # Using the new environment file approach instead of set-output
          OUTPUTS=$(aws cloudformation describe-stacks \
            --stack-name text-to-sql-chatbot \
            --query "Stacks[0].Outputs" \
            --output json \
            --region ap-south-1)
          echo "STACK_OUTPUTS<<EOF" >> $GITHUB_ENV
          echo "$OUTPUTS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
          # Display outputs in table format for readability in logs
          aws cloudformation describe-stacks \
            --stack-name text-to-sql-chatbot \
            --query "Stacks[0].Outputs" \
            --output table \
            --region ap-south-1
      
      - name: Display API Endpoint
        run: |
          API_ENDPOINT=$(echo '${{ env.STACK_OUTPUTS }}' | jq -r '.[] | select(.OutputKey=="ApiEndpoint") | .OutputValue')
          echo "Your API is deployed at: $API_ENDPOINT"
          echo "API_ENDPOINT=$API_ENDPOINT" >> $GITHUB_ENV
